### ISSUE TITLE
Eslint

### ISSUE THREAD

**Issue by IlyaZha** [bhbs/viject#38]
I like your project, it helped me to migrate from react-scripts to vite without problems. Thank you!  One thing I would like to add. React-scripts includes eslint with eslint config. But it stopped working after migration. 
To fix it I installed these packages: `vite-plugin-eslint eslint-config-react-app vite-plugin-checker` and added  `eslint()` to `vite.config.ts`

**Comment by bhbs** [comment]
Thank you! Good idea.
I'll implement it before Vite v5 comes out 😀

**Comment by bhbs** [comment]
I thought about it again, but I've decided not to implement it after all.
Viject keeps react-scripts after migration, which means that the `eslint` command can be used without additional settings in Vite. While it is convenient that react-scripts runs automatically at build time, I don't want to introduce bugs in other parts of app building. I've decided to give up on migrating from Jest to Vitest too.

Anyway, Thank you for your suggestion!
